Бот упал с ошибкой: list index out of range
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
0
Бот запущен
Бот запущен
0
Бот запущен
0
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот запущен
Бот отправил сообщение
Бот запущен
Бот отправил сообщение
Бот запущен
Бот запущен
Бот запущен
Бот упал с ошибкой: object of type 'NoneType' has no len()
Бот запущен
Бот упал с ошибкой: object of type 'NoneType' has no len()
Бот запущен
Бот упал с ошибкой: object of type 'NoneType' has no len()
Бот запущен
Бот упал с ошибкой: object of type 'NoneType' has no len()
Бот запущен
Бот упал с ошибкой: object of type 'NoneType' has no len()
Бот запущен
Other error: Expecting value: line 1 column 1 (char 0)
Бот упал с ошибкой: 
Бот запущен
Other error: Expecting value: line 1 column 1 (char 0)
Бот упал с ошибкой: 
Бот запущен
Other error: Expecting value: line 1 column 1 (char 0)
Бот упал с ошибкой: 
Бот запущен
Other error: Expecting value: line 1 column 1 (char 0)
Бот упал с ошибкой: 
Бот запущен
Other error: HTTPSConnectionPool(host='praktikum.yandex.ru', port=443): Max retries exceeded with url: /api/user_api/homework_statuses/3?from_date=1630216221 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff675f21320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Бот упал с ошибкой: Other error: HTTPSConnectionPool(host='praktikum.yandex.ru', port=443): Max retries exceeded with url: /api/user_api/homework_statuses/3?from_date=1630216221 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff675f21320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Бот запущен
Other error: HTTPSConnectionPool(host='praktikum.yandex.ru', port=443): Max retries exceeded with url: /api/user_api/homework_statuses/3?from_date=1630216263 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60e0192f28>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Бот упал с ошибкой: Other error: HTTPSConnectionPool(host='praktikum.yandex.ru', port=443): Max retries exceeded with url: /api/user_api/homework_statuses/3?from_date=1630216263 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f60e0192f28>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Бот запущен
Other error: Expecting value: line 1 column 1 (char 0)
Бот упал с ошибкой: Other error: Expecting value: line 1 column 1 (char 0)
Бот запущен
Other error: Expecting value: line 1 column 1 (char 0)
Бот упал с ошибкой: Other error: Expecting value: line 1 column 1 (char 0)
Бот запущен
Other error: Expecting value: line 1 column 1 (char 0)
Бот упал с ошибкой: Other error: Expecting value: line 1 column 1 (char 0)
Бот запущен
Other error: Expecting value: line 1 column 1 (char 0)
Бот упал с ошибкой: Other error: Expecting value: line 1 column 1 (char 0)
Бот запущен
Бот запущен
